### ISSUE TITLE
[Almost Complete] Feedback on Assignment

### ISSUE THREAD

**Issue by jah2488** [1Power/blog#1]
- Is this app on github, I'd love to see the live site.
- Your `root` url should be at the bottom of your routes file always
- It doesn't look like it is possible to create new users or messages in this app, the controllers are virtually empty.
- There are *no* validations or associations in your models.

**Comment by 1Power** [comment]
Still editing. Have to fix those errors.

**Comment by jah2488** [comment]
No worries, make sure you are paying attention in there and not on work right now.

**Comment by 1Power** [comment]
Fulfilled all requirements listed:https://basecamp.com/1940253/projects/7973405/messages/36567016#comment_250619661

https://limitless-reef-6340.herokuapp.com/
